### PR TITLE
cli: install dependencies as dev deps

### LINKED ISSUE #1304: Dependencies like bits-ui should be installed as devDependencies and not dependencies
### Describe the bug

When deploying SvelteKit sites using adapter-node, whether you use dependencies or devDependencies matter. devDependencies get bundled by Rollup, while normal dependencies are left in node_modules and externalized. By default, when adding components with `npx  shadcn-svelte@latest add` dependencies like bits-ui are added to dependencies when it's preferential that they be in devDependencies.

> Development dependencies will be bundled into your app using [Rollup](https://rollupjs.org/). To control whether a given package is bundled or externalised, place it in devDependencies or dependencies respectively in your package.json.

https://kit.svelte.dev/docs/adapter-node#deploying

This is a follow-up on https://github.com/huntabyte/shadcn-svelte/issues/580 which was closed because I think it was not correctly interpreted. 

### Reproduction

-

### Logs

_No response_

### System Info

```bash
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M2
    Memory: 79.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v22.9.0/bin/npm
  Browsers:
    Chrome: 129.0.6668.90
    Safari: 18.0.1
    Safari Technology Preview: 18.0
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.6.2 
    bits-ui: ^0.21.16 => 0.21.16 
    lucide-svelte: ^0.447.0 => 0.447.0 
    svelte: ^4.2.7 => 4.2.19
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by huntabyte**
Closes #1304

### CODE REVIEW

**Review by AdrianGonz97 — APPROVED** [review]

**Comment by ieedan** [comment]
I didn't see you were working on this. 

I have pretty much the same thing but I upgraded `package-manager-detector` to `0.2.2` so we could use the `resolveCommand` api.

**Comment by huntabyte** [comment]
> I didn't see you were working on this.
> 
> I have pretty much the same thing but I upgraded `package-manager-detector` to `0.2.2` so we could use the `resolveCommand` api.

Thank you! We can refactor to use `resolveCommand` in the `@next` branch.

**Comment by ieedan** [comment]
> > I didn't see you were working on this.
> > I have pretty much the same thing but I upgraded `package-manager-detector` to `0.2.2` so we could use the `resolveCommand` api.
> 
> Thank you! We can refactor to use `resolveCommand` in the `@next` branch.

Opened #1319 on `@next`

**Comment by filiabel** [comment]
Should this apply to `svelte-headless-table` as well?

https://www.shadcn-svelte.com/docs/components/data-table#installation

**Pull request merged**
