### PR TITLE
fix: pagination overflowing

### LINKED ISSUE #600: Pagination component overflowing its container on mobile devices
### Change Type

Correction

### Proposed Changes

As you can see in the screenshot, on mobile devices the pagination component overflows the container:
Overflowing pagination

I marked this as a docs issue since a user of this component can easily change the number of pages shown on mobile screens as they desire.

### PR DESCRIPTION
**Pull request by HubbeDev**
This pr attempts to fix #600. Im not 100% sure this is the right way to go. 

Feel free to come with feedback if their is a better approach. 

### The fix includes

Hide every page item except current page item and ellipsis.
I also hide the "Previous" and "Next" labels on small screen to make it more tidy. 

### Before submitting the PR, please make sure you do the following

- [x] If your PR isn't addressing a small fix (like a typo), it references an issue where it is discussed ahead of time and assigned to you. In many cases, features are absent for a reason.
- [x] Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- [x] This message body should clearly illustrate what problems it solves.
- [x] Follows the [contribution guidelines](https://github.com/huntabyte/shadcn-svelte/blob/main/CONTRIBUTING.md).
- [x] Format & lint the code with `pnpm format` and `pnpm lint`

### CODE REVIEW

**Comment by huntabyte** [comment]
Hey @HubbeDev, thanks for taking this on! I don't think we should change the `<Pagination.XX>` components. We should just update the `pagination-demo` files to ensure it is responsive.

**Review by huntabyte — CHANGES_REQUESTED** [review]
Let's just update the demos to be responsive rather than the individual components. Those can remain as they are in the `main` branch!

**Comment by huntabyte** [comment]
Actually what we could do is update the pagination next button and previous buttons to keep the existing API the same, but move it into a slot fallback, so something like this:

```svelte
<PaginationPrimitive.PrevButton asChild let:builder>
	<Button
		variant="ghost"
		class={cn("gap-1 pl-2.5", className)}
		builders={[builder]}
		on:click
		{...$$restProps}
	>
		<slot>
			<ChevronLeft class="h-4 w-4" />
			<span class="hidden sm:block">Previous</span>
		</slot>
	</Button>
</PaginationPrimitive.PrevButton>
```

This way, in our updated `pagination-demo` components, we could do something like:

```svelte
<Pagination.Item>
			<Pagination.PrevButton>
				<ChevronLeft class="h-4 w-4" />
				<span class="hidden sm:block">Previous</span>
			</Pagination.PrevButton>
</Pagination.Item>
```

And the same would go for the next button of course.

**Comment by HubbeDev** [comment]
@huntabyte I have moved the logic outside the components now with a slot instead. 
I didn't know that svelte-legos look awesome. But I'm not 100% sure if this is the best way. The code works and updates the pagination but only on load. Not resize. So if the page is loaded on a desktop the pagination will still overflow when resizing the window.

**Comment by huntabyte** [comment]
Oh, this is actually a bug with `bits-ui`, the options aren't being updated with the new props. Let me push a patch fix to bits and this should resolve itself with a version update.

**Review by huntabyte — APPROVED** [review]

**Comment by huntabyte** [comment]
Just pushed a commit that fixes this issue! Thanks a ton @HubbeDev, you're greatly appreciated!

**Pull request merged**
