### PR TITLE
fix: Mistake in Table guide #275

### PR DESCRIPTION
**Pull request by philippviereck**
fixes: #275 

- I updated the docs and the svelte-components I found to use: `Table.Display` instead of `Table.Column` where needed.
- I also updated the line-numbers for the code highlighting as well as minor adaptions in the text as a result of the code changes.
- I changed `export const payments: Payment[] = [` to `export const data: Payment[] = [` to be consistent with the rest of the guide.
- I moved `type Payment` 

NOTE:
I'm not really sure if this is the proper way to access and pass the data as a prop, maybe @bryanmylee can double check:
```
cell: ({ row }, { data }) => {
        const payment = derived(data, ($data) => $data[Number(row.id)]);
        return createRender(DataTableActions, {
          payment
        });
      }
```

Also, now that `Table.Display` is used instead of `Table.Column` there's this weird behaviour that when hiding the email column all rows disappear see: https://github.com/bryanmylee/svelte-headless-table/issues/160

 feedback and review on these changes are greatly appreciated

### CODE REVIEW

**Comment by philippviereck** [comment]
I just found: https://github.com/huntabyte/shadcn-svelte/pull/297. Let me know how to continue.

**Comment by huntabyte** [comment]
Let's see what @jeffpohlmeyer has to say, maybe you could wrap up his PR if he doesn't have the time, either way I appreciate the contribution!

**Comment by jeffpohlmeyer** [comment]
I've been busy with work for the past week and a half and haven't had a chance to update mine. I'll take a look in the morning but if this addresses the shortcomings of mine then I'm happy to close my PR

**Comment by philippviereck** [comment]
I think my PR addresses everything @jeffpohlmeyer.

But before merging these should be solved/agreed upon (see my initial comment):
- Best practice to access / pass data when using `table.display()`
- https://github.com/bryanmylee/svelte-headless-table/issues/160

**Comment by huntabyte** [comment]
Hey @philippviereck,

You should be able to get the row's ID using some type narrowing helper functions provided by the library,  [here](https://svelte-headless-table.bryanmylee.com/docs/api/body-row#isdisplay-boolean).

So something like:

```ts
cell: ({ row }) => {
	if (row.isDisplay()) {
		// now I know the type and can access row.original
		return createRender(DataTableActions, {
          payment: row.original.id
        });
	}
}
```

For that issue you tagged, I remember that being a pain in the ass for me as well when building it out. I want to say it has something to do with the filter or sort, and ensuring they are disabled for all columns that don't need them. I was really hoping that switching to `table.display` would fix it for some reason, but I guess that's not the case.

**Pull request closed without merging**
