### PR TITLE
fix(next): Update command doesn't update component code

### LINKED ISSUE #1368: Failed to fetch registry from https://next.shadcn-svelte.com/registry
### Describe the bug

Running  npx  shadcn-svelte@next update

◇  Which components would you like to update?
│  avatar, badge, button, card, checkbox, command, context-menu, dialog, dropdown-menu, form, input, label, popover, radio-group, select, separator, sheet, skeleton, sonner, switch, table, tabs, utils
│
◇  Ready to update components? (Make sure you have committed your changes before proceeding!)
│  Yes
│
└  [CLI Error]: Failed to fetch registry from https://next.shadcn-svelte.com/registry.

### Reproduction

 npx  shadcn-svelte@next update

### Logs

_No response_

### System Info

```bash
System:
    OS: Windows 11 10.0.26100
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 4.64 GB / 31.91 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 9.12.2 - C:\ProgramData\chocolatey\bin\pnpm.EXE
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.26100.1882
```

### Severity

blocking an upgrade

### PR DESCRIPTION
**Pull request by ieedan**
If you ran `npx shadcn-svelte@next update` before you would notice that even though it completes successfully it doesn't actually update the code for any components.

PS: This sounds super rude reading it back but I can't think of a better way to word it so it's really not intentional

+ Also Closes #1368

### CODE REVIEW

**Comment by ieedan** [comment]
I am going to try and add a few tests before it merges working on that now

**Comment by ieedan** [comment]
Tests are done so should be all good now!

**Comment by ieedan** [comment]
@huntabyte Let me know if I should take a look at #1368. 

Is the expected behavior to just remove `utils` from the update list or should we actually make it work?

**Comment by ieedan** [comment]
> @huntabyte Let me know if I should take a look at #1368.
> 
> Is the expected behavior to just remove `utils` from the update list or should we actually make it work?

For not I just made it so that if the user selected utils we just remove utils from the end of the selectedComponents array so that we don't try and later fetch it from the registry.

**Comment by ieedan** [comment]
fixes #1368

**Comment by huntabyte** [comment]
Thanks @ieedan!  We've discussed removing the `update` command altogether as it is a bit redundant to `add`, but I'm going to let @AdrianGonz97 make the call on this one.

**Comment by ablesea** [comment]
> Thanks @ieedan! We've discussed removing the `update` command altogether as it is a bit redundant to `add`, but I'm going to let @AdrianGonz97 make the call on this one.

I think it is still useful especially when I have a big project and I don't want to type out every component it's a bit more ergonomic to choose each component to update.

**Comment by AdrianGonz97** [comment]
Thanks for the PR! I'll be sure to give this a review over the weekend

**Comment by AdrianGonz97** [comment]
this is excellent. thank you!!

**Review by AdrianGonz97 — APPROVED** [review]

**Pull request merged**
