### PR TITLE
Feat/tasks example

### PR DESCRIPTION
**Pull request by HubbeDev**
Done some updates to the tasks example.

**Added:**
1. Pagination
2. Serach functionality
3. Toggle hidden columns

Reference: #362 

Edit: Im not sure that i should have done the merge from main. Let me know if it was wrong.

### CODE REVIEW

**Comment by huntabyte** [comment]
Hey @HubbeDev, the combobox and command are now added if you still have the cycles to finish this! You'll want to merge upstream main with your branch to make sure everything is synced up. Let me know if you run into any issues, definitely want to get this example out there!

**Comment by HubbeDev** [comment]
@huntabyte Perfect! I notised that they where added. Got much going on last couple of days. But got some time over tonight.

**Comment by HubbeDev** [comment]
@huntabyte Added the comboboxes and started to work on the column filter. Got a bit stuck at how to implement the column filter combined with the comboboxes haven't gotten the time to dig deeper into svelte headless table yet.

Will continue tomorrow. Feel free to implement it if you have the time before me.

**Comment by HubbeDev** [comment]
@huntabyte The filters is added now.  Let me know if anything is missing.

**Review by huntabyte — APPROVED** [review]
Incredible job! @HubbeDev thanks a ton for this, looks so good!

**Pull request merged**
