### PR TITLE
fix: styles for `Select.Trigger`

### PR DESCRIPTION
**Pull request by JabSYsEmb**
Fix an issue in "/themes" page - report issue component:
Screenshot 2024-03-15 at 21 19 03
"line-clamp-1" is setting the display to "-webkit-box" which overwrite the "flex" class therefore I have remove "line-clamp-1" from the classes and add "overflow-hidden" instead.

Closes: #1020

### CODE REVIEW

**Review by huntabyte — APPROVED** [review]

**Comment by huntabyte** [comment]
Thank you! @JabSYsEmb

**Comment by Scooter1337** [comment]
2 things:
- Truncate already sets overflow to hidden, 'overflow-hidden' is not doing anything.
- ui.shadcn.com/themes uses line-clamp-1 too, do you have the same issue there?

**Comment by JabSYsEmb** [comment]
@Scooter1337 
image

I wasn't aware that truncate sets the overflow to hidden, but surprisingly ui.shadcn.com/themes looks fine to me even though they merge "flex" + "line-camp-1"  together.  

I just noticed that ui.shadcn.com uses an old version of tailwind-merge:
```js
{
		"tailwind-merge": "^1.12.0",
}
```
whereas shadcn-svelte uses:
```js
{
		"tailwind-merge": "^2.2.1",
}
```

if you update the tailwind-merge dependency you'll face the same issue as here
Screenshot 2024-03-18 at 11 24 38

**Comment by huntabyte** [comment]
What's the verdict here?

**Comment by JabSYsEmb** [comment]
The "overflow-hidden" class is redundant as "truncate" also sets the overflow to "hidden".

**Comment by Scooter1337** [comment]
@JabSYsEmb could you lint, format and push so the checks are all green? 😃

**Pull request merged**
