### PR TITLE
Feat/update playground example

### PR DESCRIPTION
**Pull request by HubbeDev**
Ref: #453

### CODE REVIEW

**Comment by huntabyte** [comment]
Hey @HubbeDev, thanks for tackling this! For some reason, the search doesn't appear to be properly filtering on the "Model Selector", when I type "text" it shows "No results found.".

**Comment by HubbeDev** [comment]
Hey @huntabyte . Aha i notice that as well. Will take a look at it when I get back from my holiday next week.

**Comment by huntabyte** [comment]
Thank you! @HubbeDev

**Comment by HubbeDev** [comment]
@huntabyte [22b5103](https://github.com/huntabyte/shadcn-svelte/pull/477/commits/22b5103c340d6181e1df91e2719d74f9c68afc1c) Fixes the problem.

**Comment by huntabyte** [comment]
Incredible @HubbeDev!!

**Review by huntabyte — APPROVED** [review]

**Pull request merged**
