### PR TITLE
feat: update icon imports/`radix-icons-svelte` -> `svelte-radix`

### PR DESCRIPTION
**Pull request by shyakadavis**
### Before submitting the PR, please make sure you do the following

Fixes: #575 

For faster load times & builds, icons will now be imported as such:

```svelte
import Circle from 'lucide-svelte/icons/circle';
```
P.S.
With the ```"moduleResolution: "Bundler"``` option, the TS compiler was screaming its lungs out due to `svelte-headless-table`. I updated it given the new release https://github.com/bryanmylee/svelte-headless-table/releases/tag/v0.18.0, and updated some type imports, and all is well now.

- [x] If your PR isn't addressing a small fix (like a typo), it references an issue where it is discussed ahead of time and assigned to you. In many cases, features are absent for a reason.
- [x] Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- [x] This message body should clearly illustrate what problems it solves.
- [x] Follows the [contribution guidelines](https://github.com/huntabyte/shadcn-svelte/blob/main/CONTRIBUTING.md).
- [x] Format & lint the code with `pnpm format` and `pnpm lint`

### CODE REVIEW

**Comment by AdrianGonz97** [comment]
So far so good! Turns out that I didn't have to adjust the registry script at all as we handle the dependencies for icons a little differently. 

In regards to the current `svelte-check` error, it looks like the form error is originating from `formsnap`. Currently working on that in this PR: https://github.com/huntabyte/formsnap/pull/111

As soon as that's merged and released, we can merge this PR.

**Comment by shyakadavis** [comment]
Glad to hear.

Best of luck, stranger. 🙂

**Comment by huntabyte** [comment]
https://github.com/ciscoheat/sveltekit-superforms/releases/tag/v1.13.2 Superforms has exposed the type for this now.

**Comment by huntabyte** [comment]
Alrighty, I've merged in `main` to get rid of those merge conflicts.

Since there doesn't seem to be a Radix Icons for Svelte with proper exports setup I'll look into spinning something up this week.

**Comment by huntabyte** [comment]
Swapped `radix-icons-svelte` out with [svelte-radix](https://github.com/shinokada/svelte-radix).

### Default style

```diff
- import { Check } from 'lucide-svelte'
+ import Check from 'lucide-svelte/icons/check'
```

### New York style

```diff
- import { Check } from 'radix-icons-svelte'
+ import Check from 'svelte-radix/Check.svelte'
```

**Comment by huntabyte** [comment]
Thanks a ton peeps! @shyakadavis @AdrianGonz97

**Review by huntabyte — APPROVED** [review]

**Pull request merged**
