### PR TITLE
fix: check icon in checkbox is off-center

### LINKED ISSUE #313: Checkbox Check is off-centered
### Current Behavior

The checkbox check is slightly off-center.

Screenshot 2023-09-21 at 8 51 41 PM

### Expected Behavior

The checkbox check is smack in the middle of the box itself.

Screenshot 2023-09-21 at 8 52 03 PM

### Steps To Reproduce

Add this component to a page and check it, or set it to be. checked programatically.

### Link to Reproduction / Stackblitz

_No response_

### More Information

I was able to get this centered up by adding tw class `box-content` to the `CheckboxPrimitive.Root` component, and changing all of the `h-4 w-4` classes to `h-3.5 w-3.5` in order to preserve the height of the checkbox.

### PR DESCRIPTION
**Pull request by wlockiv**
closes #313

### CODE REVIEW

**Comment by huntabyte** [comment]
Is this only the case for the `default` style checkbox? @wlockiv

**Comment by wlockiv** [comment]
@huntabyte i could be missing something here, but i don't see any variants set up for checkbox, unless you mean something different?

**Comment by huntabyte** [comment]
Hey @wlockiv, there are two styles, `Default` and `New York`, just want to confirm this issue doesn't also exist for New York!

**Comment by wlockiv** [comment]
Lol I completely forgot 🙃. 

Just updated the PR.

**Comment by wlockiv** [comment]
@huntabyte I've updated the NY style and also fixed the formatting issues causing GH actions to fail from last week.

**Comment by huntabyte** [comment]
> @huntabyte I've updated the NY style and also fixed the formatting issues causing GH actions to fail from last week.

Thanks for this!

**Pull request merged**
