### PR TITLE
feat: Using a Proxy to Fetch from shadcn Registry

### PR DESCRIPTION
**Pull request by shahradelahi**
#401

### CODE REVIEW

**Comment by huntabyte** [comment]
Hey there @shahradelahi this is great! Do you think it's worth adding that this support exists to the CLI documentation?

**Comment by shahradelahi** [comment]
Hi there,

I'm not entirely certain, but I added a `--proxy` flag to the `add` command. However, it might be helpful to log a warning message, so that the user knows whether they are using a proxy or not.

Please let me know if you think any further changes are needed.

**Comment by huntabyte** [comment]
Thanks for this! I more so meant within the https://shadcn-svelte.com/docs/cli page which gives instructions on how to use with a proxy!

**Comment by huntabyte** [comment]
Is this good to go? @shahradelahi

**Review by huntabyte — APPROVED** [review]

**Comment by shahradelahi** [comment]
@huntabyte, In the preview deployment, the document section that I added is not being displayed. Other than that, everything looks good to go. Thank you for the review. 🌷

**Pull request merged**
