### PR TITLE
feat ✨: Enhance Copy Button Functionality and UI with Persistent Package Manager Selection

### PR DESCRIPTION
**Pull request by Michael-Obele**
This pull request addresses issue #1059 by introducing a persistent package manager selection feature. The user's chosen package manager is now saved and automatically used across pages within a session, improving user experience and reducing friction.

**Key Improvements:**

* **Dynamic Command Selection:** The component now dynamically updates the `selectedCommand` value when a command is copied.
* **UI Enhancements:** The button's UI has been improved to display the selected command with the `CaretSort` icon, providing a clearer visual indication.
* **Bug Fixes:** The `handleCopyDone` function has been corrected to ensure accurate updating of the `selectedCommand` value.
* **Persistent Package Manager Selection:** User preferences for the package manager are now stored using a writable store for easy retrieval. This eliminates the need for repeated prompts and improves user experience.

**Changes:**

* Integrated `selectedCommand` writable store to manage user preferences.
* Updated `copy-button.svelte` to use the selected package manager and dynamically update `selectedCommand`.
* Enhanced UI to display the selected command with `CaretSort` icon and allow modification of the package manager.
* Fixed `handleCopyDone` function for accurate `selectedCommand` updates.

**Testing:**

* Thoroughly tested the component's functionality to ensure the selected package manager is persisted across pages, and `selectedCommand` is updated correctly.
* Verified that the UI changes are visually appealing and provide a clear indication of the selected command and package manager.

**Showcase**

[Screencast.webm](https://github.com/user-attachments/assets/550a9741-c4d5-4988-94b4-8129b2825372)

### CODE REVIEW

**Comment by huntabyte** [comment]
@Michael-Obele, thanks a ton for this, I will give it a review!

**Comment by Michael-Obele** [comment]
> @Michael-Obele, thanks a ton for this, I will give it a review!

Glad to help. Looking forward to the review.

**Comment by huntabyte** [comment]
Closing for #1257 as you opened this PR on your `main` branch and it doesn't let me push changes easily to the PR. Your original commits are still included in the new PR though 😃

Thanks a ton for this! I added some improvements to actually render the correct commands in the code blocks based on the PM!

**Comment by Michael-Obele** [comment]
Thanks a ton. My bad, didn't know that would happen

**Pull request closed without merging**
