### PR TITLE
fix(next): resolve command for sveltekit sync as `execute-local`

### LINKED ISSUE #1486: Feature Request(CLI): Using custom `.svelte-kit` locations
### Describe the bug

I am using non-default setup for sveltekit where files are not in .svelte-kit. When I run `pnpm dlx shadcn-svelte@next add ...` the command fails at `pnpm dlx svelte-kit sync` with `ERR_PNPM_DLX_NO_BIN  No binaries found in svelte-kit`.

This is my svelte.config.js file:
```
const config = {
  kit: {
    ...
    files: {
      hooks: {
        universal: process.env.CLIENT ? 'src/client/hooks' : 'src/admin/hooks',
        server: process.env.CLIENT ? 'src/client/hooks.server' : 'src/admin/hooks.server',
        client: process.env.CLIENT ? 'src/client/hooks.client' : 'src/admin/hooks.client'
      },
      routes: process.env.CLIENT ? 'src/client/routes' : 'src/admin/routes'
    },
    outDir: `.dist.${process.env.CLIENT ? 'client' : 'admin'}`
  },
  ...
}
```

NOTE: I am using the `next` version of shadcn

### Reproduction

1. Create a new SvelteKit project
2. Set `files` property to non-default values in `svelte.config.js`
3. Run shadcn cli to set it up with the project

### Logs

```bash
ERR_PNPM_DLX_NO_BIN  No binaries found in svelte-kit
```

### System Info

```bash
MacOS
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by ieedan**
Fixes #1486. 

Sorry about the misunderstanding I skipped like 2 words reading the issue and totally threw me off.

### CODE REVIEW

**Comment by AdrianGonz97** [comment]
thank you! mind adding a changeset as well? (i would, but the changeset bot seems to be taking a day off since it didn't respond to this PR)

**Comment by ieedan** [comment]
> thank you! mind adding a changeset as well? (i would, but the changeset bot seems to be taking a day off since it didn't respond to this PR)

Well it is Friday lol

**Comment by ieedan** [comment]
There you go my bad!

Looks like the bot has also decided to participate now

**Comment by AdrianGonz97** [comment]
excellent. thank you!

**Pull request merged**
