### PR TITLE
docs: Update tasks example to be 1:1 with original

### PR DESCRIPTION
**Pull request by Scooter1337**
### Before submitting the PR, please make sure you do the following

- [x] If your PR isn't addressing a small fix (like a typo), it references an issue where it is discussed ahead of time and assigned to you. In many cases, features are absent for a reason.
- [x] Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- [x] This message body should clearly illustrate what problems it solves.
- [x] Format & lint the code with `pnpm format` and `pnpm lint`

Before:
ss1

After:
ss2

### CODE REVIEW

**Comment by huntabyte** [comment]
Hey there, thanks for taking the time to knock this out! I think we should update it to align with the original

**Comment by Scooter1337** [comment]
> Hey there, thanks for taking the time to knock this out! I think we should update it to align with the original

Excuse me, I must have hallucinated the text. Fixed it, and made it 1:1 with the original.

**Comment by Scooter1337** [comment]
ss3
Columns now hidable via header, also added icons to Asc and Desc, matching the original.

**Comment by Scooter1337** [comment]
@huntabyte Could you look at my implementation of the 'Hide column' header functionality? I might be overcomplicating it.:

- now passing tableModel and cell.id to DataTableColumnHeader
- DataTableColumnHeader uses tableModel and cell.id to add the cell.id to hiddenCollumnIds
- DataTableViewOptions now watches for changes in tableModel's hiddenCollumnIds

**Comment by Scooter1337** [comment]
Found out that 'Desc' always toggled 'Ascending' if props.sort.order was undefined. As there is no 'set' but only toggle, we now toggle twice if 'Desc' and props.sort.order === undefined. (undefined -> 'Asc' -> 'Desc')

**Pull request merged**
