### PR TITLE
feat: expose `scrollSnaps` `selectedIndex` `scrollTo`

### PR DESCRIPTION
**Pull request by shyakadavis**
> Had briefly touched on this is in the server, bringing it here for your consideration;

This P.R lays the groundwork necessary to create a dots-scroll-to feature like in the video. From now on, one need only reach into the context and grab these stores+function and style however they wish.

```ts
const { scrollTo, scrollSnaps, selectedIndex } = getEmblaContext('<Carousel.Dots/>');
```

It's pretty easy to set up yourself, but having it come with the `carousel` component saves some time. 🙂 
(And I don't think this introduction violates/deviates from the original, wouldn't you agree? - at least components-wise)

---

https://github.com/huntabyte/shadcn-svelte/assets/87414827/bc054fdc-503d-4e57-9801-0628366cdbc0

### Before submitting the PR, please make sure you do the following

- If your PR isn't addressing a small fix (like a typo), it references an issue where it is discussed ahead of time and assigned to you. In many cases, features are absent for a reason.
- Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- This message body should clearly illustrate what problems it solves.
- Format & lint the code with `pnpm format` and `pnpm lint`

### CODE REVIEW

**Review by huntabyte — APPROVED** [review]
Thank you!

**Comment by danpii** [comment]
Hi @shyakadavis,
I am trying to create a _<Carousel.Dots/>_ component but can't get my head around on how to implement it in a clean way to also update the active dot, when the prev or next buttons are clicked.
I guess I need to use _selectedScrollSnap()_ on the API?

Do you maybe have an example?

**Comment by shyakadavis** [comment]
Hello, @danpii 

Sure. Here is my `lib/components/ui/carousel/carousel-dots.svelte` file. Just make sure to remove the `snake_case` variable names and replace with the ones from shad. Let me know if it works out.

```svelte
<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements';
	import { crossfade } from 'svelte/transition';
	import { cubicInOut } from 'svelte/easing';
	import { Button } from '../button';
	import { getEmblaContext } from './context';
	import { cn } from '$lib/utils';

	type $$Props = HTMLAttributes<HTMLDivElement>;

	let className: $$Props['class'] = undefined;
	export { className as class };

	const { handleKeyDown, scroll_to, scroll_snaps, selected_index } =
		getEmblaContext('<Carousel.Dots/>');

	const [send, receive] = crossfade({
		duration: 250,
		easing: cubicInOut
	});
</script>

<div class="absolute bottom-32 right-28 hidden h-9 items-center gap-2 md:flex">
	{#each $scroll_snaps as _, i}
		{@const is_active = $selected_index === i}
		<Button
			size="icon"
			on:click={() => scroll_to(i)}
			on:keydown={handleKeyDown}
			variant="accent"
			class={cn(
				'relative size-3 touch-manipulation rounded-full bg-border/10 transition-colors ease-linear hover:bg-border/30',
				className
			)}
		>
			{#if is_active}
				<div
					class={cn('absolute inset-0 rounded-full bg-border/60')}
					in:send={{ key: 'active_slide' }}
					out:receive={{ key: 'active_slide' }}
				/>
			{/if}
		</Button>
	{/each}
</div>
```

**Comment by danpii** [comment]
Thanks for you quick reply @shyakadavis!

Looks good and the _scrollTo_ is working correctly. The only thing that's not working yet is the _active bullet_. 
It seems` {@const is_active = $selectedIndex === i}` is not updated correctly. The _is_active_ div is always shown inside the first bullet button.
Any advice? Do I need to make an adjustment on the parent component as well?

**Comment by shyakadavis** [comment]
Hmm... hard for me to summarise without looking at some code, but my guess is that the `selectedIndex` store isn't being updated whenever you select an option.

Inside `carousel.svelte` make sure you're doing just that.

```diff
//
++ const selectedIndex = writable(0);
//
function onSelect(api: CarouselAPI) {
		if (!api) return;
		canScrollPrev.set(api.canScrollPrev());
		canScrollNext.set(api.canScrollNext());
++		selectedIndex.set(api.selectedScrollSnap());
	}
//
$: if (api) {
++		onSelect(api);
++		api.on('select', onSelect);
++		api.on('reInit', onSelect);
	}
//
```

If this is the issue, I wonder if I forgot to add this store in the P.R. Please confirm if it is.

**Comment by danpii** [comment]
Thanks again, really appreciated! It works now!

In this PR (#1052 )you added:
`const selectedIndexStore = writable(0);`

This part was already in the code (if I see it correctly):
```
$: if (api) {
	onSelect(api);
	api.on("select", onSelect);
	api.on("reInit", onSelect);
}
```


So all I had to do was:

```diff

function onSelect(api: CarouselAPI) {
	if (!api) return;
	canScrollPrev.set(api.canScrollPrev());
	canScrollNext.set(api.canScrollNext());
+	selectedIndexStore.set(api.selectedScrollSnap());
}
```

**Comment by shyakadavis** [comment]
Snap. Thought I had covered this.

Thank you for confirming. If I get time soon I'll open a follow-up P.R. (Or if you have the time right now, you could help.)

Regardless, thank you.

**Comment by danpii** [comment]
I can try as in the course of this week

**Comment by shyakadavis** [comment]
https://github.com/huntabyte/shadcn-svelte/pull/1289

**Pull request merged**
