### PR TITLE
fix: Some flags were being incorrectly assigned to config values

### PR DESCRIPTION
**Pull request by ieedan**
- Fixes an bug when using flags created by #1186

Some config values were being set to the tailwindConfig flag

Recreate with the following command
```
npm run start -- init -c testing --style new-york --base-color zinc --css src/app.css --tailwind-config tailwind.config.ts --components-alias '$lib/components' --utils-alias '$lib/utils.ts'
```

Gives this error:
```
[Config Error]: Invalid import alias found: ("utils": "tailwind.config.ts") in components.json.
   - Import aliases must use existing path aliases defined in your tsconfig.json (e.g. "utils": "$lib/utils").
   - See: https://www.shadcn-svelte.com/docs/installation/manual#configure-path-aliases.
```

I have renamed the flags and added a changeset for a patch.

### CODE REVIEW

**Comment by ieedan** [comment]
@AdrianGonz97 if you have a chance can you take a look at this

**Comment by AdrianGonz97** [comment]
Ah, completely my fault. Thanks for the fix!

**Comment by AdrianGonz97** [comment]
FYI: it looks like github actions are super slow/at a standstill atm, so it might be a bit before the versioning PR is opened and a new release is cut. I'll keep an eye out for it as soon as it does 👍

**Comment by ieedan** [comment]
> github actions are super slow/at a standstill atm

Impossible

**Comment by ieedan** [comment]
We may need to restart the runners they seem to be frozen and GitHub is reporting normal now.

**Comment by AdrianGonz97** [comment]
Yea, that workflow was completely bugged out. I couldn't even restart it, github was ignoring all requests to manually restart it. Instead, I had to make a new PR to retrigger the workflow. It should be good to go now

**Pull request merged**
