### PR TITLE
🎨 style(DashboardPage.svelte): adjust column span for Recent Sales ca…

### PR DESCRIPTION
**Pull request by mactanxin**
fix Recent Sales card span in `md` and smaller view

### CODE REVIEW

**Comment by mactanxin** [comment]
in the dashboard example page, the two cards are not aligned when viewport's width is smaller than `1024px`

**Comment by huntabyte** [comment]
Thank you @mactanxin !

**Comment by mactanxin** [comment]
@huntabyte Hi, is there anything I need to do about this PR? Or other issues 😉

**Comment by huntabyte** [comment]
hey @mactanxin -  there was actually a big merge that should have addressed this! If not, please let me know!

**Pull request closed without merging**
