### PR TITLE
feat: Switch to TanStack Table

### PR DESCRIPTION
**Pull request by shyakadavis**
Closes: #1189 

I wonder if we should wait for the Svelte 5 version, though? If that's the case, happy to close this and wait for it. 🙂 

TODO:

- [ ] If/when greet lit, I can try my hand at overhauling the docs for the datable, because this P.R only switches the `Tasks` example
- [x] Center text when no search result(s)
- [x] Fix faceted filters
- [x] Clean-up change functions (`onRowSelectionChange`, `onSortingChange`, `onColumnFiltersChange`, `onColumnVisibilityChange`), preferably to separate function definitions
- [x] When you select all, and then deselect at least one row, the header's checkbox remains checked. This is because `checked` isn't reacting to changes to `table.getIsAllPageRowsSelected() || (table.getIsSomePageRowsSelected() && 'indeterminate')`. Will keep investigating.
- [x] Figure how generics play into this - I forewent using them because I kept running into weird TS errors, and used the `Task` type instead.
- [ ] Move from the `/tasks-2` route to `/tasks`
- [ ] Changed the file names to shorter/clear ones, because I often find it hard to locate a file (I know `cmd+p` is the way to go), but you know, 🤷 I can revert to the old way, though 🙂 

---

### Before submitting the PR, please make sure you do the following

- If your PR isn't addressing a small fix (like a typo), it references an issue where it is discussed ahead of time and assigned to you. In many cases, features are absent for a reason.
- Prefix your PR title with `feat:`, `fix:`, `chore:`, or `docs:`.
- This message body should clearly illustrate what problems it solves.
- Format & lint the code with `pnpm format` and `pnpm lint`

### CODE REVIEW

**Comment by kaechele** [comment]
Nice! I started working on this in parallel but you beat me to it. My solution is very close to what you have.

Generics should technically be straightforward. Here's what works for me.
You'd add `generics="TData, TValue"` to your `<script lang="ts">` and:

- your `data` is now `TData[]` instead of `Task[]`
- `Table<Task>` becomes a `Table<TData>`
- your `ColumnDef<Task>` become a `ColumnDef<TData, TValue>`
- a `Column<Task>` is now a `Column<TData, TValue>`

One could think about pulling the column definition out of the components. This is what I ended up doing.
Composing the `Task` table specific cells into the table happens in the column definitions anyway. That way the base components become more reusable.

**Comment by shyakadavis** [comment]
Hey, @kaechele 

It's my first time working with TanStack-anything, so glad I wasn't far off with how others are doing it. 😅 

> You'd add generics="TData, TValue" to your <script lang="ts">

Yup. This is what I was doing, but when it came to passing props in the column defs, weird errors came up. Which leads me to:

> One could think about pulling the column definition out of the components.

Sure. I could look into this. Thanks.

> Composing the Task table specific cells into the table happens in the column definitions anyway. That way the base components become more reusable.

Hmm... can I trouble you with a snippet of this? Can't get my head around what you mean, yet.

> EDIT: I'm actually working on this using @tanstack/svelte-table@alpha and Svelte 5, so a few things are a bit different to account for the Svelte 5 changes. In hindsight, I should have probably added a YMMV to the generics part. Haven't tested it with the older versions.

I'm actually wondering if I should just wait for Svelte 5 as well. I guess I'm doing it now in case it's easier when migrating to S5. 🤷

**Comment by c-kirkeby** [comment]
In the TanStack docs they recommend using [column helpers](https://tanstack.com/table/v8/docs/guide/column-defs#column-helpers) for building column definitions which are quite similar to the API from svelte-headless-table. I believe the rationale is that they provide a higher type safety.

**Comment by entrenadorhispano** [comment]
TanStack, as soon as I understand, Will not be supported out of the box on svelte 5. 
 https://github.com/sveltejs/svelte/issues/10359#issue-2111964532
 
 Be aware of this issue.

**Comment by shyakadavis** [comment]
> In the TanStack docs they recommend using [column helpers](https://tanstack.com/table/v8/docs/guide/column-defs#column-helpers) for building column definitions

Ah. Thanks a lot, @c-kirkeby Will change this in a few.

**Comment by shyakadavis** [comment]
@kaechele 

Before I commit my interpretation of this:

> One could think about pulling the column definition out of the components.

Did you mean doing something like this:

header.svelte
```svelte
	type $$Props = HTMLAttributes<HTMLDivElement> & {
		title: string;
		canSort: boolean;
		isSorted: boolean | 'asc' | 'desc' | boolean;
		toggleSorting: (desc?: boolean, isMulti?: boolean) => void;
		toggleVisibility: (v: boolean) => void;
	};
```

and in columns.ts
```ts
columnHelper.accessor('id', {
		id: 'task',
		header: ({ column }) => {
			return renderComponent(ColumnHeader, {
				title: 'Task',
				canSort: column.getCanSort(),
				isSorted: column.getIsSorted(),
				toggleSorting: column.toggleSorting,
				toggleVisibility: column.toggleVisibility
			});
		},
		enableSorting: false,
		enableHiding: false
	}),
```

**Comment by c-kirkeby** [comment]
Okay so rather than doubling up on trying to convert the Tasks demo, I implemented the Data Table for my own project here at https://github.com/c-kirkeby/osrs-price-site/pull/3. It doesn't have the filter or the actions / row selection or the filters from the Tasks example, and mine has some more complex use cases like colouring cells / right-aligning cells.

One issue I ran into was this:
https://github.com/c-kirkeby/osrs-price-site/pull/3/files#diff-dfcbcef4795391b3fac61ea52dc73d867264ba430a9ea6dfcab677acd7777e66R72-R73

Due to TanStack/table#4382 there are some TypeScript errors when assigning `columns` to the `ColumnDef<TData, TValue>` type.

**Comment by shyakadavis** [comment]
Closing as this has been shipped in the `next` branch. 🎉 (PR: #1318)

**Pull request closed without merging**
